app.py
import json
from flask import Flask, render_template, session
from blueprint_query.routes import blueprint_query
from blueprint_auth.routes import blueprint_auth
from access import login_required

app = Flask(__name__)
with open('configs/db.json') as f:
    app.config['db_config'] = json.load(f)

with open('configs/access.json') as f:
    app.config['access_config'] = json.load(f)

app.secret_key = 'SuperKey'

app.register_blueprint(blueprint_query, url_prefix='/query')
app.register_blueprint(blueprint_auth, url_prefix='/auth')


@app.route('/')
@login_required
def main_menu():
    if session.get('user_group', None):
        return render_template('internal_menu.html')
    return render_template('external_menu.html')


@app.route('/exit')
@login_required
def exit_func():
    session.clear()
    return render_template('exit.html')


if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5001, debug=True)

blueprint_auth/routes.py
import os
from typing import Optional, Dict

from flask import (
    Blueprint, request,
    render_template, current_app,
    session, redirect, url_for
)

from database.operations import select
from database.sql_provider import SQLProvider

blueprint_auth = Blueprint(
    'blueprint_auth',
    __name__,
)

provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@blueprint_auth.route('/', methods=['GET', 'POST'])
def start_auth():
    if request.method == 'GET':
        return render_template('templates_bp_auth/input_login.html', message='')
    else:
        login = request.form.get('login')
        password = request.form.get('password')
        if login:
            user_info = define_user(login, password)
            if user_info:
                user_dict = user_info[0]
                session['user_id'] = user_dict['user_id']
                session['user_group'] = user_dict['user_group']
                session.permanent = True
                return redirect(url_for('main_menu'))
            else:
                return render_template('templates_bp_auth/input_login.html', message='Пользователь не найден')
        return render_template('templates_bp_auth/input_login.html', message='Повторите ввод')


def define_user(login: str, password: str) -> Optional[Dict]:
    sql_internal = provider.get('internal_user.sql', login=login, password=password)
    sql_external = provider.get('external_user.sql', login=login, password=password)

    user_info = None

    for sql_search in [sql_internal, sql_external]:
        _user_info = select(current_app.config['db_config'], sql_search)
        print(_user_info)
        if _user_info:
            user_info = _user_info
            del _user_info
            break
    return user_info

blueprint_query/routes.py
import os
from flask import Blueprint, render_template, request, current_app
from work_with_db import select_dict
from sql_provider import SQLProvider

blueprint_query = Blueprint('bp_query', __name__)
provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@blueprint_query.route('/')
def query_menu():
    return render_template('query_menu.html')


@blueprint_query.route('/banquet_report', methods=['GET', 'POST'])
def banquet_report():
    if request.method == 'GET':
        return render_template('requests/input_param.html')
    else:
        _month = request.form.get('month')
        _year = request.form.get('year')
        _sql = provider.get('banquet_report.sql', month=_month, year=_year)
        order = select_dict(current_app.config['db_config'], _sql)
        print(order)
        if order:
            prod_title = "Results:"
            return render_template('requests/banquet_report.html', orders=order, prod_title=prod_title)
        else:
            return render_template('requests/no_results.html')


@blueprint_query.route('/manager_report', methods=['GET', 'POST'])
def manager_report():
    if request.method == 'GET':
        return render_template('requests/input_param.html')
    else:
        _sql = provider.get('manager_report.sql')
        manager_data = select_dict(current_app.config['db_config'], _sql)
        if manager_data:
            prod_title = "Results:"
            return render_template('requests/manager_report.html',
                                   manager=manager_data, prod_title=prod_title)
        else:
            return render_template('requests/no_results.html')


@blueprint_query.route('/youngest_manager', methods=['GET'])
def youngest_manager():
    _sql = provider.get('youngest_manager.sql')
    manager_data = select_dict(current_app.config['db_config'], _sql)
    if manager_data:
        prod_title = 'Youngest manager data:'
        return render_template('requests/manager_data.html', manager=manager_data, prod_title=prod_title)
    else:
        return render_template('requests/no_results.html')


@blueprint_query.route('/manager_without_orders', methods=['GET', 'POST'])
def manager_without_orders():
    if request.method == 'GET':
        return render_template('requests/input_param.html')
    else:
        _month = request.form.get('month')
        _year = request.form.get('year')
        _sql = provider.get('manager_without_orders.sql', month=_month, year=_year)
        manager_data = select_dict(current_app.config['db_config'], _sql)
        if manager_data:
            prod_title = 'The lazy managers are:'
            return render_template('requests/manager_data.html', manager=manager_data, prod_title=prod_title)
        else:
            return render_template('requests/no_results.html')

blueprint_report/routes.py
import os

from flask import (
    Blueprint, render_template,
    request, current_app,
    session, redirect, url_for
)

from access import group_required
from database.operations import select, call_procedure
from database.sql_provider import SQLProvider

blueprint_report = Blueprint(
    'blueprint_report',
    __name__,
)

provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@blueprint_report.route('/', methods=['GET'])
@group_required
def index():
    return render_template('reports/base.html')


@blueprint_report.route('/report', methods=['GET'])
@group_required
def work_report():
    return render_template('reports/chosen_report.html')


@blueprint_report.route('/create', methods=['GET', 'POST'])
@group_required
def create_report():
    if request.method == 'GET':
        return render_template('reports/date_form.html')
    else:
        db_config = current_app.config['db_config']

        year = request.form.get('year')
        month = request.form.get('month')

        sql = provider.get('select_report_date.sql', year=year, month=month)
        reports = select(db_config, sql)

        if reports:
            return render_template('reports/date_form.html',
                                   error='Такой отчёт уже существует')

        reports = call_procedure(db_config, 'create_otchet', year, month)

        if not reports:
            return render_template('reports/date_form.html',
                                   error=f'Отчёт не создан. За {month}-{year} заказов нет.')

        return render_template('reports/successful_report.html', year=year, month=month)


@blueprint_report.route('/view/<date>', methods=['GET'])
@group_required
def view_report(date):
    db_config = current_app.config['db_config']

    year = int(date[:4])
    month = int(date[5:])

    sql = provider.get('select_report_date.sql', year=year, month=month)
    reports = select(db_config, sql)

    return render_template('reports/report_view.html', reports=reports, date=date)

templates/exceptions/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Доступ закрыт</title>
</head>
<body>
    {% block internal_users %}{% endblock %}
    {% block external_users %}{% endblock %}
    <a href="/">В главное меню</a>
</body>
</html>

templates/exceptions/external_only.html
{% extends 'exceptions/base.html' %}

{% block internal_users %}
<div>
    <h1>Данный ресурс доступен только для покупателей</h1>
    <p>Вам необходимо зайти в личный кабинет, чтобы получить сюда доступ</p>
</div>
{% endblock %}

templates/exceptions/internal_only.html
{% extends 'exceptions/base.html' %}

{% block external_users %}
<div>
    <h1>Данный ресурс доступен только для сотрудников</h1>
    <p>Запросите доступ у администратора или войдите под учетной записью сотрудника</p>
</div>
{% endblock %}

templates/exit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="../static/css/bootstrap.css" rel="stylesheet">
    <title>До свидания</title>
</head>
<body>
<div style="text-align: center">
    <h1>Вы вышли из системы</h1>
    <a role="button" class="btn btn-danger" href="/">Вернуться в меню входа</a>
</div>
</body>
</html>

templates/external_menu.html
{% extends 'layouts/base.html' %}

{% block content %}
    <p style="text-align: center">
        <a href=""> В Каталог </a>
        <br><br>
        <a role="button" class="btn btn-danger" href="/exit">Завершить сессию</a>
    </p>
{% endblock %}

templates/internal_menu.html
{% extends 'layouts/base.html' %}

{% block content %}

    <p style="text-align: center">

        <a href="{{ url_for('bp_query.query_menu') }}"> Работать с запросами... </a>
        <br><br>
        <a href=""> В Каталог </a>
        <br><br>
        <a role="button" class="btn btn-danger" href="/exit">Завершить сессию</a>
    </p>

{% endblock %}

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base_menu</title>
    <link href="../../static/css/bootstrap.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div style="text-align: center;">
        <h1 style="text-align: center"> Вам доступны следующие действия </h1>
        {% block content %}

            Place for content here

        {% endblock %}
    </div>
</body>
</html>

templates/main_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Menu</title>
    <link href="../static/css/bootstrap.css" rel="stylesheet" type="text/css">
</head>
<body>
<div style="text-align: center;">
    <h2> Заказ Банкета </h2>
    <br><br>
    <a href="{{ url_for('bp_query.query_menu') }}"> Работать с запросами... </a>
    <br><br>
    <a href=""> В Каталог </a>
    <br><br>
    <a role="button" class="btn btn-danger" href="/exit">
        Завершить сессию</a>
</div>
</body>
</html>

templates/query_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Запросы</title>
    <link href="../static/css/bootstrap.css" rel="stylesheet" type="text/css">
</head>
<body>
<div style="text-align: center;">
    <h2> Запросы </h2>
    <a href="{{ url_for('bp_query.banquet_report') }}">
        Составить отчёт о банкетах за выбранный месяц и год</a>
    <br><br>
    <a href="{{ url_for('bp_query.manager_report') }}">
       Составить отчёт о работе менеджеров за выбранный месяц и год</a>
    <br><br>
    <a href="{{ url_for('bp_query.youngest_manager') }}">
       Вывести данные о самом молодом менеджере</a>
    <br><br>
    <a href="{{ url_for('bp_query.manager_without_orders') }}">
       Вывести данные о менеджере без заказов в выбранном месяце</a>
    <br><br>
    <a href="{{ url_for('main_menu') }}" class="btn btn-danger" role="button">В Главное Меню</a>
</div>
</body>
</html>

templates/reports/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/reports/chosen_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/reports/date_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/reports/report_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/reports/successful_report.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/reports/view_all_reports.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/requests/banquet_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Max Price</title>
    <link href="../../static/css/bootstrap.css" rel="stylesheet" type="text/css">

    <style>
        td {
            text-align: center;
        }
    </style>
</head>
<body>
<div style="text-align: center">
    <h2>{{ prod_title }}</h2>
    <table style="margin: auto">
        <tr class="tab_title">
            <td>Дата проведения</td>
            <td>Название зала</td>
            <td>Начальная стоимость</td>
            <td>Конечная стоимость</td>
            <td>Фамилия ответственного менеджера</td>
        </tr>
        {% for order in orders %}
            <tr>
                <td>{{ order['orderDate'] }}</td>
                <td>{{ order['hallName'] }}</td>
                <td>{{ order['avans'] }}</td>
                <td>{{ order['realPrice'] }}</td>
                <td>{{ order['surname'] }}</td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('main_menu') }}" class="btn btn-danger" role="button">В Главное Меню</a>
</div>
</body>
</html>

templates/requests/input_param.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Max Price</title>
    <link href="../../static/css/bootstrap.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h2 style="text-align: center">Введите параметры поиска</h2>
            <br>
            <form action="" method="post">
                <div class="form-group">
                    <label for="month">Месяц</label>
                    <input type="text" class="form-control" name="month" id="month"
                           placeholder="Введите месяц" required>
                </div>
                <br>
                <div class="form-group">
                    <label for="year">Год</label>
                    <input type="text" class="form-control" name="year" id="year"
                           placeholder="Введите год" required>
                </div>
                <br>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary" style=:>Отправить</button>
                </div>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
</body>
</html>

templates/requests/manager_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Youngest manager</title>
    <link href="../../static/css/bootstrap.css" rel="stylesheet" type="text/css">

    <style>
        td {
            text-align: center;
            margin-right: 10px;
        }
        tables {
            margin: 20px;
        }
    </style>
</head>
<body>
<div style="text-align: center">
    <h2> {{ prod_title }}</h2>
    <table style="margin: auto">
        <tr class="tab_title" style="text-align: center">
            <td>Id</td>
            <td>Имя</td>
            <td>Фамилия</td>
            <td>Дата устройства</td>
            <td>Дата увольнения</td>
            <td>Дата рождения</td>
            <td>Возраст</td>
        </tr>
        {% for _manager in manager %}
        <tr class="tab-content" style="text-align: center">
            <td>{{ _manager['idmanager'] }}</td>
            <td>{{ _manager['name'] }}</td>
            <td>{{ _manager['surname'] }}</td>
            <td>{{ _manager['employmentDate'] }}</td>
            <td>{{ _manager['resignDate'] }}</td>
            <td>{{ _manager['birthday'] }}</td>
            <td>{{ _manager['Age'] }}</td>
        </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('main_menu') }}" class="btn btn-danger" role="button">В Главное Меню</a>
</div>
</body>
</html>

templates/requests/manager_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manager report</title>
    <link href="../../static/css/bootstrap.css" rel="stylesheet" type="text/css">

    <style>
        td {
            text-align: center;
        }
    </style>
</head>
<body>
<div style="text-align: center">
    <h2> {{ prod_title }}</h2>
    <table style="margin: auto">
        <tr class="tab_title" style="text-align: center">
            <td>Id менеджера</td>
            <td>Фамилия</td>
            <td>Общее количество принятых заказов</td>
            <td>Общая сумма принятых заказов</td>
        </tr>
        {% for _manager in manager %}
            <tr>
                <td>{{ _manager['idmanager'] }}</td>
                <td>{{ _manager['surname'] }}</td>
                <td>{{ _manager['order_num'] }}</td>
                <td>{{ _manager['full_price'] }}</td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('main_menu') }}" class="btn btn-danger" role="button">В Главное Меню</a>
</div>
</body>
</html>

templates/requests/no_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="../../static/css/bootstrap.css" rel="stylesheet" type="text/css">
    <title>Нет результатов</title>
</head>
<body>
<div style="text-align: center;">
        <h2 style="color: crimson"> Нет результатов по данному запросу </h2>
        <br>
        <a href="{{ url_for('main_menu') }}" class="btn btn-danger" role="button">Вернуться В Главное Меню</a>
</div>
</body>
</html>

templates/templates_bp_auth/input_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authentication</title>
    <link href="../../static/css/bootstrap.css" type="text/css" rel="stylesheet">
</head>
<body>
  <h1 style="text-align: center"> Введите логин и пароль</h1> <br><br>
  <div style="text-align: center">
      <form method="POST" action="">
          <label for="login"> Логин</label>
          <input type="text" id="login" name="login" required><br><br>

          <label for="password"> Пароль </label>
          <input type="password" name="password" id="password" required><br><br>

          <input type="submit" class="submit" value="Отправить">
      </form>
      <br><br>
      <h2 align="center">{{ message }}</h2>
  </div>
</body>
</html>

templates/templates_bp_auth/refuse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      <h1 align="center">
         Вам отказано в доступе
      </h1>  <br><br>
      <a href={{url_for('menu_choice')}}>Нажмите для возврата к меню</a>

</body>
</html>

templates/teplates_bp_query/dynamic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>supermarket</title>
    <style>
        div {
            text-align: center;
        }
        table {
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <link href="sem2.css" rel="stylesheet" type="text/css">
</head>
<body>
<div>
    <h2> {{prod_title}}</h2>
    <table>
        <tr class = "tab_title">
            <td>Название</td>
            <td>Единица измерения</td>
            <td>Цена</td>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{product['prod_name']}}</td>
            <td>{{product['prod_measure']}}</td>
            <td>{{product['prod_price']}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

templates/teplates_bp_query/input_param.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="" rel="stylesheet" type="text/css"/>
</head>
<body>
<center>
    <h2>Введите параметры поиска</h2>
    <form action="" method=post>
        <label for="cat">Категория товара</label> <!-- фор в лейбле связывается с конкретным полем ввода -->
        <input type="text" name="category" id="cat"><br><br>
        <label for="price">Цена</label>
        <input type="text" name="price" id="price">
        <br><br>
        <input type="submit" class="button" value="Отправить">
    </form>
</center>
</body>
</html>